# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 01:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='app_branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.IntegerField(choices=[(0, 'new'), (1, 'assigned'), (2, 'integrated'), (3, 'released')], default=1)),
                ('purpose', models.TextField()),
                ('dev_list', models.CharField(max_length=50)),
                ('qa_list', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='app_integration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='app_version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20)),
                ('status', models.IntegerField(choices=[(0, 'packaged'), (1, 'package_fail'), (2, 'deployed'), (3, 'deploy_fail'), (4, 'tested'), (5, 'test_fail'), (6, 'released'), (7, 'release_fail'), (8, 'verified'), (9, 'verify_fail')], default=0)),
                ('note', models.TextField()),
                ('comments', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('status', models.IntegerField(choices=[(0, 'offline'), (1, 'online')], default=1)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('version', models.CharField(max_length=20)),
                ('version_prefix', models.CharField(max_length=20)),
                ('scm_tool', models.CharField(max_length=20)),
                ('repo_url', models.URLField(max_length=300)),
                ('deploy_path', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('status', models.IntegerField(choices=[(0, 'new'), (1, 'assigned'), (2, 'integrated'), (3, 'released')], default=1)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apollo_release.Applications')),
            ],
        ),
        migrations.CreateModel(
            name='prod_version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20)),
                ('create_time', models.DateTimeField()),
                ('owner', models.CharField(max_length=20)),
                ('note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('status', models.IntegerField(choices=[(0, 'offline'), (1, 'online')], default=1)),
                ('create_time', models.DateTimeField()),
                ('owner', models.CharField(max_length=20)),
                ('version', models.CharField(max_length=20)),
                ('note', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='prod_version',
            name='prod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apollo_release.product'),
        ),
        migrations.AddField(
            model_name='application',
            name='prod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apollo_release.product'),
        ),
        migrations.AddField(
            model_name='app_version',
            name='prod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apollo_release.application'),
        ),
        migrations.AddField(
            model_name='app_integration',
            name='version',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apollo_release.app_version'),
        ),
        migrations.AddField(
            model_name='app_branch',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apollo_release.application'),
        ),
        migrations.AddField(
            model_name='app_branch',
            name='integration',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apollo_release.app_integration'),
        ),
    ]
