# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apollo_release', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prod_version',
            name='prod',
        ),
        migrations.RemoveField(
            model_name='product',
            name='version',
        ),
        migrations.AddField(
            model_name='application',
            name='auto_test_job',
            field=models.URLField(default='null', max_length=300),
        ),
        migrations.AddField(
            model_name='application',
            name='package_job',
            field=models.URLField(default='null', max_length=300),
        ),
        migrations.DeleteModel(
            name='prod_version',
        ),
    ]
