# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 10:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('apollo_release', '0002_app_branch_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_branch',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 6, 16, 10, 54, 7, 581064, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
