# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apollo_release', '0002_auto_20160614_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='deploy_path',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='repo_url',
            field=models.URLField(default='null', max_length=300),
        ),
        migrations.AlterField(
            model_name='application',
            name='scm_tool',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='version',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='version_prefix',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
