# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-17 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apollo_release', '0005_application_repo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_branch',
            name='owner_list',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='app_integration',
            name='progress',
            field=models.CharField(default='null', max_length=500),
        ),
        migrations.AlterField(
            model_name='app_integration',
            name='status',
            field=models.CharField(default='null', max_length=20),
        ),
    ]
