# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-17 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apollo_release', '0006_auto_20160617_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='deploy_type',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
