# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-17 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apollo_release', '0007_application_deploy_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='deploy_job',
            field=models.URLField(default='null', max_length=300),
        ),
    ]
