# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apollo_release', '0008_application_deploy_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='code_type',
            field=models.CharField(default='null', max_length=20),
        ),
    ]
