# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 08:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apollo_release', '0009_application_code_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='app_dev_node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(default='null', max_length=50)),
                ('env_name', models.CharField(default='null', max_length=50)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('commit', models.CharField(default='null', max_length=50)),
                ('created_by', models.CharField(default='aji', max_length=50)),
                ('package_status', models.CharField(default='null', max_length=20)),
                ('deploy_status', models.CharField(default='null', max_length=20)),
                ('test_status', models.CharField(default='null', max_length=20)),
                ('package_log', models.CharField(default='null', max_length=200)),
                ('deploy_log', models.CharField(default='null', max_length=200)),
                ('test_log', models.CharField(default='null', max_length=200)),
                ('app', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apollo_release.application')),
                ('branch', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apollo_release.app_branch')),
            ],
        ),
    ]
