# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 08:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apollo_cmdb', '0002_auto_20160621_0612'),
        ('apollo_release', '0010_app_dev_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_dev_node',
            name='env',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apollo_cmdb.app_env'),
        ),
    ]
