# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apollo_release', '0011_app_dev_node_env'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_dev_node',
            name='status',
            field=models.CharField(default='new', max_length=50),
        ),
    ]
