# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apollo_release', '0012_app_dev_node_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_dev_node',
            name='archive_url',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
