# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apollo_release', '0013_app_dev_node_archive_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_dev_node',
            name='version',
            field=models.CharField(default='null', max_length=20),
        ),
    ]
