# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-23 08:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apollo_release', '0014_app_dev_node_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='app_int_node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(default='null', max_length=50)),
                ('dev_branch_list', models.CharField(default='null', max_length=100)),
                ('progress', models.CharField(default='null', max_length=500)),
                ('status', models.CharField(default='null', max_length=20)),
                ('comments', models.TextField(default='null')),
                ('sit_env_name', models.CharField(default='null', max_length=50)),
                ('sit_env_id', models.IntegerField(default=1)),
                ('sit_archive_url', models.CharField(default='null', max_length=200)),
                ('sit_package_status', models.CharField(default='null', max_length=20)),
                ('sit_deploy_status', models.CharField(default='null', max_length=20)),
                ('sit_test_status', models.CharField(default='null', max_length=20)),
                ('sit_package_log', models.CharField(default='null', max_length=200)),
                ('sit_deploy_log', models.CharField(default='null', max_length=200)),
                ('sit_test_log', models.CharField(default='null', max_length=200)),
                ('pre_env_name', models.CharField(default='null', max_length=50)),
                ('pre_env_id', models.IntegerField(default=1)),
                ('pre_archive_url', models.CharField(default='null', max_length=200)),
                ('pre_package_status', models.CharField(default='null', max_length=20)),
                ('pre_deploy_status', models.CharField(default='null', max_length=20)),
                ('pre_test_status', models.CharField(default='null', max_length=20)),
                ('pre_package_log', models.CharField(default='null', max_length=200)),
                ('pre_deploy_log', models.CharField(default='null', max_length=200)),
                ('pre_test_log', models.CharField(default='null', max_length=200)),
                ('beta_env_name', models.CharField(default='null', max_length=50)),
                ('beta_env_id', models.IntegerField(default=1)),
                ('beta_archive_url', models.CharField(default='null', max_length=200)),
                ('beta_package_status', models.CharField(default='null', max_length=20)),
                ('beta_deploy_status', models.CharField(default='null', max_length=20)),
                ('beta_test_status', models.CharField(default='null', max_length=20)),
                ('beta_package_log', models.CharField(default='null', max_length=200)),
                ('beta_deploy_log', models.CharField(default='null', max_length=200)),
                ('beta_test_log', models.CharField(default='null', max_length=200)),
                ('online_env_name', models.CharField(default='null', max_length=50)),
                ('online_env_id', models.IntegerField(default=1)),
                ('online_archive_url', models.CharField(default='null', max_length=200)),
                ('online_package_status', models.CharField(default='null', max_length=20)),
                ('online_deploy_status', models.CharField(default='null', max_length=20)),
                ('online_test_status', models.CharField(default='null', max_length=20)),
                ('online_package_log', models.CharField(default='null', max_length=200)),
                ('online_deploy_log', models.CharField(default='null', max_length=200)),
                ('online_test_log', models.CharField(default='null', max_length=200)),
                ('app', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apollo_release.application')),
            ],
        ),
        migrations.AlterField(
            model_name='app_branch',
            name='status',
            field=models.IntegerField(choices=[(0, 'open'), (1, 'ready_integrate'), (2, 'integrated'), (3, 'released'), (4, 'ignored')], default=1),
        ),
        migrations.AlterField(
            model_name='branch',
            name='status',
            field=models.IntegerField(choices=[(0, 'open'), (1, 'ready_integrate'), (2, 'integrated'), (3, 'released'), (4, 'ignored')], default=1),
        ),
        migrations.AddField(
            model_name='app_int_node',
            name='release_branch',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='apollo_release.app_branch'),
        ),
    ]
