# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-23 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apollo_release', '0016_app_int_node_commit'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_branch',
            name='integrated_in',
            field=models.IntegerField(default=1),
        ),
    ]
