# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 10:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apollo_release', '0018_app_branch_env'),
    ]

    operations = [
        migrations.CreateModel(
            name='app_process_dev',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_package', models.CharField(default='true', max_length=10)),
                ('auto_deploy', models.CharField(default='true', max_length=10)),
                ('auto_test', models.CharField(default='true', max_length=10)),
                ('app', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apollo_release.application')),
            ],
        ),
        migrations.CreateModel(
            name='app_process_release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_env', models.CharField(default='yes', max_length=10)),
                ('auto_package_pre', models.CharField(default='true', max_length=10)),
                ('auto_deploy_pre', models.CharField(default='true', max_length=10)),
                ('beta_env', models.CharField(default='yes', max_length=10)),
                ('auto_package_beta', models.CharField(default='true', max_length=10)),
                ('auto_deploy_beta', models.CharField(default='true', max_length=10)),
                ('auto_test_pre', models.CharField(default='true', max_length=10)),
                ('pre_confirm', models.CharField(default='manual', max_length=10)),
                ('online_env', models.CharField(default='yes', max_length=10)),
                ('auto_package_online', models.CharField(default='true', max_length=10)),
                ('auto_deploy_online', models.CharField(default='true', max_length=10)),
                ('auto_test_online', models.CharField(default='true', max_length=10)),
                ('online_confirm', models.CharField(default='manual', max_length=10)),
                ('app', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apollo_release.application')),
            ],
        ),
        migrations.CreateModel(
            name='app_process_sit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_package', models.CharField(default='true', max_length=10)),
                ('auto_deploy', models.CharField(default='true', max_length=10)),
                ('auto_test', models.CharField(default='true', max_length=10)),
                ('app', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apollo_release.application')),
            ],
        ),
    ]
