# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apollo_release', '0019_app_process_dev_app_process_release_app_process_sit'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_process_release',
            name='auto_test_beta',
            field=models.CharField(default='true', max_length=10),
        ),
    ]
