# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apollo_release', '0020_app_process_release_auto_test_beta'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_process_release',
            name='beta_confirm',
            field=models.CharField(default='manual', max_length=10),
        ),
    ]
