# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 06:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apollo_cmdb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app_env',
            old_name='ip_lists',
            new_name='ip_list',
        ),
    ]
