# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 09:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('status', models.IntegerField(choices=[(0, 'new'), (1, 'developing'), (2, 'integrated'), (3, 'released')], default=0)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branch.Applications')),
            ],
        ),
    ]
